version: '2'

services:

  artemis:
    image: rmohr/activemq
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: password
#    networks:
#      - amqp-quickstart-network